version: '2'
services:
  zabbix-ext-all-templates:
    image: monitoringartist/zabbix-ext-all-templates:latest
  grafana-xxl:
    ports:
      - 3000:3000
    image: monitoringartist/grafana-xxl:latest

  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    volumes:
      - zabbix-db-storage:/var/lib/mysql
      - backups:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=my_password

  zabbix-server:
    image: monitoringartist/zabbix-xxl:latest
    depends_on:
      - zabbix-db
    ports:
      - "81:80"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/usr/local/share/zabbix/alertscripts
    volumes_from:
      - zabbix-ext-all-templates
    links:
      - zabbix-db:zabbix.db
    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=zabbix
      - ZS_DBPassword=my_password
volumes:
  zabbix-db-storage:
    driver: local
  backups:
    driver: local
