version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 18080:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
